{"DoctorURI": "https://www.healthgrades.com/physician/dr-emily-dossett-2chfr", "Doctor_Name": "Dr. Emily Dossett, MD", "Doctor_Speciality": "Psychiatry", "Doctor_Age": "", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(888) 515-3500", "Doctor_Address": "Lac Usc Medical Center: 2250 Alcazar St Ste 2200 Los Angeles, CA 90089", "Doctor_Score": "3.7"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-kwang-park-2bwh5", "Doctor_Name": "Dr. Kwang Park, MD", "Doctor_Speciality": "Psychiatry", "Doctor_Age": "73", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 769-6100", "Doctor_Address": "Hollywood Mental Health Center: 1224 Vine St Los Angeles, CA 90038", "Doctor_Score": "4.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-milica-stefanovic-3b3cn", "Doctor_Name": "Dr. Milica Stefanovic, MD", "Doctor_Speciality": "Psychiatry", "Doctor_Age": "66", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(323) 644-1998", "Doctor_Address": "Ambrose Hills Wellness: 4448 AMBROSE AVE Los Angeles, CA 90027", "Doctor_Score": "4.6"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-steven-schenkel-3kbxq", "Doctor_Name": "Dr. Steven Schenkel, MD", "Doctor_Speciality": "Psychiatry", "Doctor_Age": "71", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(310) 659-8884", "Doctor_Address": "Steven S Schenkel MD: 116 N Robertson Blvd Los Angeles, CA 90048", "Doctor_Score": "3.2"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-collins-liu-yr35r", "Doctor_Name": "Dr. Collins Liu, MD", "Doctor_Speciality": "Neurology", "Doctor_Age": "", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 442-6870", "Doctor_Address": "Hcc I I 3000: 1520 San Pablo St Ste 3000 Los Angeles, CA 90033", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-christopher-giza-x9jjf", "Doctor_Name": "Dr. Christopher Giza, MD", "Doctor_Speciality": "Neurology", "Doctor_Age": "55", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(310) 825-0867", "Doctor_Address": "Pediatrics Gastroenterology: 200 Medical Plz Ste 265 Los Angeles, CA 90095", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/providers/kelly-stapleton-xynvvnh", "Doctor_Name": "Kelly Stapleton, RD", "Doctor_Speciality": "Pediatric Nutrition", "Doctor_Age": "", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(310) 900-7867", "Doctor_Address": "3630 E Imperial Hwy Lynwood, CA 90262", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/providers/angana-shah-y9q62hz", "Doctor_Name": "Angana Shah, LRD", "Doctor_Speciality": "Lung Disease", "Doctor_Age": "", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(626) 991-2784", "Doctor_Address": "234 S El Molino Ave Apt 5 Pasadena, CA 91101", "Doctor_Score": "4.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-david-quinn-3d6vp", "Doctor_Name": "Dr. David Quinn, MD", "Doctor_Speciality": "Oncology", "Doctor_Age": "57", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 865-3000", "Doctor_Address": "USC Kenneth Norris Cancer Ctr: 1441 Eastlake Ave Los Angeles, CA 90089", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-huyen-pham-3cb8b", "Doctor_Name": "Dr. Huyen Pham, MD", "Doctor_Speciality": "Oncology", "Doctor_Age": "53", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 276-3705", "Doctor_Address": "1516 San Pablo St Ste 3300 Los Angeles, CA 90033", "Doctor_Score": "4.7"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-shahrooz-eshaghian-ysdgp", "Doctor_Name": "Dr. Shahrooz Eshaghian, MD", "Doctor_Speciality": "Medical Oncology", "Doctor_Age": "40", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(310) 229-3555", "Doctor_Address": "Compassionate Oncology Med Grp: 2080 Century Park E Ste 1005 Los Angeles, CA 90067", "Doctor_Score": "4.4"}
{"DoctorURI": "https://www.healthgrades.com/providers/mary-pardee-xyp4pyw", "Doctor_Name": "Dr. Mary Pardee, NMD", "Doctor_Speciality": "Gastroenterology", "Doctor_Age": "", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(760) 932-0849", "Doctor_Address": "2080 Century Park E Los Angeles, CA 90067", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-armine-sarkisian-y387b", "Doctor_Name": "Dr. Armine Sarkisian, MD", "Doctor_Speciality": "Gastroenterology", "Doctor_Age": "54", "Doctor_Gender": "Female", "Doctor_PhoneNo": null, "Doctor_Address": "Armine Sarkisian MD: 800 S Central Ave Ste 304 Glendale, CA 91204", "Doctor_Score": "3.5"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-payman-khorrami-2lgfd", "Doctor_Name": "Dr. Payman Khorrami, MD", "Doctor_Speciality": "Gastroenterology", "Doctor_Age": "54", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(310) 553-5588", "Doctor_Address": "Payman Khorrami MD: 2080 Century Park E Ste 1108 Los Angeles, CA 90067", "Doctor_Score": "4.5"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-patrick-mullin-xpppy", "Doctor_Name": "Dr. Patrick Mullin, MD", "Doctor_Speciality": "Obstetrics & Gynecology", "Doctor_Age": "53", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 409-3306", "Doctor_Address": "USC Perinatology: 2020 Zonal Ave Los Angeles, CA 90089", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-richard-lee-3k7hd", "Doctor_Name": "Dr. Richard Lee, MD", "Doctor_Speciality": "Maternal-Fetal Medicine", "Doctor_Age": "47", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 226-3306", "Doctor_Address": "2020 Zonal Ave # 206 Los Angeles, CA 90089", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-geronimo-rodriguez-xj4gn", "Doctor_Name": "Dr. Geronimo Rodriguez, MD", "Doctor_Speciality": "Obstetrics & Gynecology", "Doctor_Age": "80", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(626) 577-8138", "Doctor_Address": "Geronimo G Rodriguez MD: 2705 Whittier Blvd Los Angeles, CA 90023", "Doctor_Score": "4.5"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-john-klutke-2qf9r", "Doctor_Name": "Dr. John Klutke, MD", "Doctor_Speciality": "Obstetrics & Gynecology", "Doctor_Age": "57", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 226-4965", "Doctor_Address": "Usc Reproductive Endocrine Laboratory: 1321 N Mission Rd Los Angeles, CA 90033", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/providers/pranathi-reddy-xylm2vb", "Doctor_Name": "Pranathi Reddy", "Doctor_Speciality": "Speech-Language Technology", "Doctor_Age": "", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(323) 404-1024", "Doctor_Address": "1111 W 6th St Ste 111 Los Angeles, CA 90017", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-vernon-williams-ypkwn", "Doctor_Name": "Dr. Vernon Williams, MD", "Doctor_Speciality": "Neurology", "Doctor_Age": "53", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(310) 665-7286", "Doctor_Address": "Vernon B. Williams, MD, Inc.: 6801 Park Ter Ste 500 Los Angeles, CA 90045", "Doctor_Score": "2.7"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-nancy-edwards-xj8c7", "Doctor_Name": "Dr. Nancy Edwards, MD", "Doctor_Speciality": "Neonatal Medicine", "Doctor_Age": "80", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(323) 226-3691", "Doctor_Address": "LAUSC Pediatrics: 2020 Zonal Ave Los Angeles, CA 90089", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-jeffrey-bender-xjpf3", "Doctor_Name": "Dr. Jeffrey Bender, MD", "Doctor_Speciality": "Infectious Disease Medicine", "Doctor_Age": "45", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 361-3500", "Doctor_Address": "Children's Hospital Central California: 4650 W Sunset Blvd Los Angeles, CA 90027", "Doctor_Score": "Not rated yet"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-david-man-3h9gx", "Doctor_Name": "Dr. David Man, MD", "Doctor_Speciality": "Infectious Disease Medicine", "Doctor_Age": "51", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(626) 793-6133", "Doctor_Address": "Infectious Disease Consultants: 50 Alessandro Pl Ste 360 Pasadena, CA 91105", "Doctor_Score": "4.6"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-emily-bloom-xxfb7", "Doctor_Name": "Dr. Emily Bloom, MD", "Doctor_Speciality": "Dermatology", "Doctor_Age": "67", "Doctor_Gender": "Female", "Doctor_PhoneNo": "(310) 278-8811", "Doctor_Address": "Simbaderm: 436 N Bedford Dr Ste 202 Beverly Hills, CA 90210", "Doctor_Score": "5.0"}
{"DoctorURI": "https://www.healthgrades.com/physician/dr-raul-simental-pizarro-3ld8h", "Doctor_Name": "Dr. Raul Simental-Pizarro, MD", "Doctor_Speciality": "Hematology", "Doctor_Age": "60", "Doctor_Gender": "Male", "Doctor_PhoneNo": "(323) 442-9611", "Doctor_Address": "Usc Neuro Interventional: 1500 San Pablo St Fl 2 Los Angeles, CA 90033", "Doctor_Score": "Not rated yet"}
