{"url": "https://www.webmd.com/drugs/2/drug-175924/inner-ear-plus-oral/details", "Brand_Name": "Inner Ear Plus", "Generic_Name": "Inositol-Choline Bit-Biofl-B-C", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-93964/ramelteon-oral/details", "Brand_Name": "Ramelteon 8 Mg Tablet Hypnotics", "Generic_Name": "COMMON BRAND(S): Rozerem", "Uses": ["sleeplessness"], "Drug Administration": "Administered via the mouth", "Side_Effects": ["dizziness", "tiredness", "daytime drowsiness"]}
{"url": "https://www.webmd.com/drugs/2/drug-93656/tipranavir-oral/details", "Brand_Name": "Tipranavir Capsule", "Generic_Name": "COMMON BRAND(S): Aptivus", "Uses": ["HIV infection", "HIV medications"], "Drug Administration": "Administered via the mouth", "Side_Effects": [", diarrhea, nausea", "vomiting", "dizziness", "headache", "drowsiness"]}
{"url": "https://www.webmd.com/drugs/2/drug-8946-8300/megestrol-oral/megestrol-suspension-oral/details", "Brand_Name": "Megestrol ACETATE", "Generic_Name": "COMMON BRAND(S): Megace", "Uses": ["loss", "weight loss", "AIDS", "appetite"], "Drug Administration": "Administered via the mouth", "Side_Effects": ["their menstrual periods", "women", "sexual ability", "unpredictable bleeding", "desire"]}
{"url": "https://www.webmd.com/drugs/2/drug-163422/pepsin-amylase-ox-bile-ext-pancreatin-betaine-papain-oral/details", "Brand_Name": "Pepsin-Amy-Ox Bile-Pan-Bet-Pap Tablet, Extended Release", "Generic_Name": "Pepsin-Amy-Ox Bile-Pan-Bet-Pap", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-153756/prevnar-13-pf-intramuscular/details", "Brand_Name": "Prevnar 13 Syringe", "Generic_Name": "Pneumoc 13-Val Conj-Dip Cr(PF)", "Uses": ["infection", "Streptococcus pneumoniae"], "Drug Administration": "Via injection into the muscles", "Side_Effects": ["injection site reactions", "fever", "(e.g., pain, redness", "swelling, hard lump", "muscle/joint aches"]}
{"url": "https://www.webmd.com/drugs/2/drug-1757-7152/oxybutynin-chloride-oral/oxybutynin-extended-release-oral/details", "Brand_Name": "Oxybutynin Chloride ER", "Generic_Name": "COMMON BRAND(S): Ditropan XL", "Uses": ["oxybutynin", "bladder", "conditions"], "Drug Administration": "Administered via the mouth", "Side_Effects": ["dry/flushed skin", "blurred vision", "dry mouth", "mouth", "stuffy nose", "cough", "constipation", "nausea", "dry eyes", "dizziness", "headache", "diarrhea", "drowsiness"]}
{"url": "https://www.webmd.com/drugs/2/drug-155344/melatonin-tryptophan-oral/details", "Brand_Name": "Melatonin-Tryptophan Capsule", "Generic_Name": "Melatonin-Tryptophan", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-6072/butisol-oral/details", "Brand_Name": "Butisol 30 Mg Tablet Hypnotics", "Generic_Name": "Butabarbital", "Uses": ["me","you","nonene"], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-163297/chlorcyclizine-oral/details", "Brand_Name": "Chlorcyclizine Tablet", "Generic_Name": "Chlorcyclizine", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-4157/dilantin-oral/details", "Brand_Name": "Dilantin 30 Mg Capsule", "Generic_Name": "Phenytoin Sodium Extended", "Uses": ["seizures"], "Drug Administration": "Administered via the mouth", "Side_Effects": ["nervousness", "vomiting", "constipation", "nausea", "dizziness", "headache", "drowsiness"]}
{"url": "https://www.webmd.com/drugs/2/drug-164611/calcium-carb-and-glucon-magnesium-oxide-and-gluconate-oral/details", "Brand_Name": "Ca Carb-Ca Gluc-Mg Ox-Mg Gluco Tablet", "Generic_Name": "Ca Carb-Ca Gluc-Mg Ox-Mg Gluco", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-16285/camphor-bulk/details", "Brand_Name": "Camphor (Bulk) Gum (Non-Oral)", "Generic_Name": "Camphor (Bulk)", "Uses": [], "Drug Administration": "", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-8499/ceftriaxone-sodium-bulk/details", "Brand_Name": "Ceftriaxone Powder", "Generic_Name": "Ceftriaxone Sodium (Bulk)", "Uses": [], "Drug Administration": "", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-3712/chloraseptic-mucous-membrane/details", "Brand_Name": "Chloraseptic Aerosol, Spray With Pump", "Generic_Name": "Phenol, Phenol-Phenolate Sodium", "Uses": [], "Drug Administration": "Via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-170279/strensiq-subcutaneous/details", "Brand_Name": "Strensiq Vial", "Generic_Name": "Asfotase Alfa", "Uses": [], "Drug Administration": "Via Injection to the Skin", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-17436/lipochol-plus-oral/details", "Brand_Name": "Lipochol Plus", "Generic_Name": "Choline-Inositol-Methion-Folic", "Uses": [], "Drug Administration": "Administered via the mouth", "Side_Effects": []}
{"url": "https://www.webmd.com/drugs/2/drug-22785/miochol-e-intraocular/details", "Brand_Name": "Miochol-E Kit", "Generic_Name": "Acetylcholine Chloride", "Uses": [], "Drug Administration": "", "Side_Effects": []}
